---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  BOSH_SSH_ENABLED:
  WINDOWS_ADMIN_PASSWORD:
  WINDOWS_ADMIN_PASSWORD_SET_PASSWORD_PASSWORD:
  SYSTEM_LOGGING:
  SYSTEM_LOGGING_ENABLE_SYSLOG_HOST:
  SYSTEM_LOGGING_ENABLE_SYSLOG_PORT:
  SYSTEM_LOGGING_ENABLE_SYSLOG_PROTOCOL:
  WINDOWS_DIEGO_CELL_PLACEMENT_TAGS:
  DIEGO_CELL_INSTANCE_TYPE:
  DIEGO_CELL_INSTANCES:
  HWC_ERRAND_INSTANCE_TYPE:
  RUNTIME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-crunchy/task.sh
