---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NAT_ENABLED:

inputs:
  - name: pipelines-repo
  - name: om-cli

run:
  path: pipelines-repo/tasks/update-metrics-ip/task.sh
