---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK_NAME:
  AZ_MULTI_SELECT:
  CONSUL_SERVER_VM_TYPE:
  CONSUL_SERVER_DISK_TYPE:
  CONSUL_SERVER_INSTANCE_COUNT:
  POSTGRESQL_HAPROXY_VM_TYPE:
  POSTGRESQL_HAPROXY_DISK_TYPE:
  SMOKE_TESTS_VM_TYPE:
  SMOKE_TESTS_DISK_TYPE:
  SMALL_VM_TYPE:
  SMALL_DISK_TYPE:
  SMALL_POSTGRESQL_INSTANCE_COUNT:
  SMALL_POSTGRESQL_SERVICE_QUOTA:
  MEDIUM_VM_TYPE:
  MEDIUM_DISK_TYPE:
  MEDIUM_POSTGRESQL_INSTANCE_COUNT:
  MEDIUM_POSTGRESQL_SERVICE_QUOTA:
  LARGE_VM_TYPE:
  LARGE_DISK_TYPE:
  LARGE_POSTGRESQL_INSTANCE_COUNT:
  LARGE_POSTGRESQL_SERVICE_QUOTA:
  EXTRA-LARGE_VM_TYPE:
  EXTRA-LARGE_DISK_TYPE:
  EXTRA-LARGE_POSTGRESQL_INSTANCE_COUNT:
  EXTRA-LARGE_POSTGRESQL_SERVICE_QUOTA:
  CRUNCHY_BROKER_INSTANCE_TYPE:
  CRUNCHY_BROKER_INSTANCES:
  CRUNCHY_BROKER_PERSISTENT_DISK_SIZE:
  ERRANDS_TO_DISABLE:
  CONCOURSE_USER:
  CONCOURSE_PWD:
  CONCOURSE_URL:
  PIPELINE-NAME:
  TEAM-NAME:
  UPGRADE-PIPELINE-NAME:


inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-crunchy/task.sh
